#!/usr/bin/env bash
set -eu

if [[ $# -gt 0 ]]
then
  cmd=$1
  shift
else
  cmd=""
fi
case "$cmd" in
"" )
  git-natp-parse "$@"
  ;;
create )
  git-natp-create "$@"
  ;;
compare )
  git-natp-compare "$@"
  ;;
esac
